baseURL: https://oblitorum.github.io
languageCode: en-us
defaultContentLanguage: en
title: The truth must be told
theme: papercss-hugo-theme
googleAnalytics: UA-184494738-1

privacy:
  disqus:
    disable: true

taxonomies:
  tag: tags

permalinks:
  posts: /:filename/

imaging:
  quality: 99

params:
  homeMetaContent: The truth must be told - Jason
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: "2006-01-02"
  navTitleLink: /

menu:
  nav:
    - name: Blog
      url: /
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
    - name: About
      url: /about/
      weight: 3
    - name: RSS
      url: /index.xml
      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2